CREATE TABLE IF NOT EXISTS articleTag (
    articleTagId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dateCreated DATETIME NOT NULL DEFAULT '0000-00-00',
    dateModified DATETIME NOT NULL DEFAULT '0000-00-00',
    tagId INT UNSIGNED NOT NULL,
    articleId INT UNSIGNED NOT NULL,
    UNIQUE INDEX idxArticleTag (tagId, articleId)
)
ENGINE = MyISAM;
